modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/wagyourtail/KeyboardLayers"
license = "MPL-2.0"

[[mods]]
modId = "bindlayers"
version = "${version}"
displayName = "Keyboard Layers"
authors = "Wagyourtail"
description = '''
Add layers to your keybinds to manage them easier
'''
logoFile = "assets/bindlayers/icon.png"

[[dependencies.bindlayers]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bindlayers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18, 1.19)"
ordering = "NONE"
side = "BOTH"